### ISSUE TITLE
mostrar qname de la ip del cliente en queries summary

### ISSUE THREAD

**Issue by camilog** [niclabs/ratadns-remy#10]

**Comment by franchoco** [comment]
Te refieres a hacer una consulta DNS inversa?

**Comment by camilog** [comment]
si, para identificar si es una IP que esta bien que haga tantas consultas (resolver) o es una IP extraña para tanta consulta

**Comment by madestro** [comment]
pedido para nuevas infoviz

**Comment by madestro** [comment]
done
