### ISSUE TITLE
mostrar solo algunos qtypes consultados y no todos (en summary)

### ISSUE THREAD

**Issue by camilog** [niclabs/ratadns-remy#12]

**Comment by franchoco** [comment]
A que te refieres con sólo algunos? 
Actualmente se muestran todos los que fueron consultados por esa IP. Te refieres a sólo mostrar los X mejores?

**Comment by camilog** [comment]
Si, después de ordenarlos, mostrar los mejores.
También puede ser mostrar los más relevantes (A, AAAA, NS, MX... no se cual mas es relevante, y dejar el resto en OTHERS)
Principalmente por el hecho que unas cajas quedan con muchísima altura y dispares unas de otras.
Otra alternativa sería mostrarlos en una lista, cosa que entre mas qtypes, no cambie mucho la altura de las cajas

**Comment by franchoco** [comment]
Me gusta la primera alternativa. La segunda fue descartada de plano por la Cote hace un tiempo: Una lista no se entiende.

**Comment by madestro** [comment]
Esto se descartó porque ahora se muestran todos los qtypes
